services:
  postgres:
    image: postgres:13
    container_name: bp22_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  spark:
    image: bitnami/spark:3.5
    container_name: bp22_spark
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "9090:8080"  # ← ubah agar UI Spark Master diakses di port 9090
    volumes:
      - ./pyspark_scripts:/opt/bitnami/spark/scripts
      - ./data:/opt/airflow/data
      - ./jars:/opt/bitnami/spark/jars  # JDBC JAR driver

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: bp22_webserver
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./pyspark_scripts:/opt/airflow/pyspark_scripts
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: bp22_scheduler
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./pyspark_scripts:/opt/airflow/pyspark_scripts
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs

volumes:
  postgres_data:
